### ISSUE TITLE
Duda sobre los conflictos generados al subir una parte del Catalogo Precios de Boletos

### ISSUE THREAD

**Issue by ReneMirandaSCO8MA111** [notei/Unimex-cinema#5]
Profesor: Alberto Farías
Me surgieron unos conflictos a la hora de sincronizar el proyecto, hice una parte de mi catálogo, con los videos que nos proporsiono el compañero alejandro entiendo que sobreescribí líneas de código y al momento de querer abrir el proyecto en Visual Studio no me lo permite, espero que me pueda a ayudar a resolver los conflictos para que mis compañeros puedan realizar sus catalogos en el proyecto.
Saludos

**Comment by notei** [comment]
Ya re establecí el proyecto, solo tienes que agregar en el menú la llamada a tu forma, no olvides poner los nombres a la forma y revisar los mesnajes que les he dejado en los issues

**Comment by ReneMirandaSCO8MA111** [comment]
Gracias por restablecer el proyecto!

**Comment by Ricardo26164** [comment]
Profe por que al querer subir mi catalogo "Productos Combos " me muestra un mensaje diciendo que 
"falla para sincronizar esta rama
es posible que necesite abrir un shell y depurar el estado de este repo"

**Comment by cbsoul** [comment]
Richi, te recomiendo hagas un nuevo clon del proyecto porque se ha restablecido un par de veces y posteriormente vuelvas a generar tu código .

**Comment by Ricardo26164** [comment]
Ok Gracias
