### ISSUE TITLE
Actualizar registros en el DataGridView

### ISSUE THREAD

**Issue by cbsoul** [notei/Unimex-cinema#6]
Al ingresar nuevos registros de nuestro catalogo,  posteriormente de hacer el Dispose de la ventana de captura me gustaría que el DGV en el form de consulta se actualizara y que mostrara el registro agregado. 

¿Cómo puedo lograr eso? 

Disculpa si no me se explicar

De antemano gracias.

**Comment by notei** [comment]
Hola Alejandro,

Tienes 2 opciones, la primera es la más limpia, que seria crear un event handler (como los que vimos en clase) para ser notificado cuando hagas el dispose de la forma, esto es en la forma donde tienes el Grid , ej

...
forma.Disposed += new EventHandler(actualizaGridView);
forma.show();

y el método actualizaGridView le pides recargar los datos de la pantalla.

La segunda opción que no es la más recomendable por que genera acoplamiento, es pasar la referencia de la forma1 a la forma2, y antes de cerrar llamar al método de actualizarDataGridView en la forma1.

Espero con esto responder a tu pregunta.

Saludos AF

**Comment by cbsoul** [comment]
utilicé el primero, me resultó mas fácil y como dice usted es más limpio, ya que no existe tanta dependencia. 

Doy por cerrado el issue
